param(
    [string]$InstallDirectory = (Join-Path $HOME "evey-stack"),
    [ValidateSet("base", "services", "full")]
    [string]$Tier = "base",
    [ValidateSet("core", "all", "skip")]
    [string]$PluginPreset = "core",
    [string]$SourceRoot,
    [switch]$SkipDockerUp
)

. "$PSScriptRoot/EveyCommon.ps1"

if (-not $SourceRoot) {
    $SourceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}

$runId = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
$logDir = Get-EveyLogDirectory -RunId $runId
$logFile = Join-Path $logDir "deploy.log"

function Get-EnvMap {
    param([Parameter(Mandatory)][string]$Path)

    $map = [ordered]@{}
    if (Test-Path -LiteralPath $Path) {
        foreach ($line in Get-Content -LiteralPath $Path) {
            if ($line -match '^\s*#' -or -not $line.Trim()) { continue }
            $parts = $line.Split("=", 2)
            if ($parts.Count -eq 2) {
                $map[$parts[0]] = $parts[1]
            }
        }
    }
    return $map
}

function Save-EnvMap {
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Map,
        [Parameter(Mandatory)][string]$Path
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Evey Stack - generated by Windows installer")
    foreach ($key in $Map.Keys) {
        $lines.Add("$key=$($Map[$key])")
    }
    $lines | Set-Content -LiteralPath $Path -Encoding UTF8
    Protect-EveyFile -Path $Path
}

function Ensure-EnvValue {
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Map,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Value
    )
    if (-not $Map.Contains($Name) -or -not $Map[$Name]) {
        $Map[$Name] = $Value
    }
}

function Copy-Template {
    param(
        [Parameter(Mandatory)][string]$RelativeSource,
        [Parameter(Mandatory)][string]$Destination
    )

    $src = Join-Path $SourceRoot $RelativeSource
    if (-not (Test-Path -LiteralPath $src)) {
        throw "Template not found: $src"
    }
    $parent = Split-Path -Parent $Destination
    if ($parent) { New-EveyDirectory -Path $parent }
    Copy-Item -LiteralPath $src -Destination $Destination -Force
}

function Remove-GpuBlockIfNeeded {
    param([Parameter(Mandatory)][string]$ComposePath)

    if (Test-EveyCommand "nvidia-smi") {
        $gpu = Invoke-EveyNative -FilePath "nvidia-smi" -Arguments @() -LogFile $logFile
        if ($gpu.ExitCode -eq 0) {
            Write-EveyLog -Message "NVIDIA GPU detected; keeping GPU compose block." -LogFile $logFile
            return
        }
    }

    $content = Get-Content -LiteralPath $ComposePath -Raw
    $pattern = '(?ms)\r?\n    deploy:\r?\n      resources:\r?\n        reservations:\r?\n          devices:\r?\n            - driver: nvidia\r?\n              count: all\r?\n              capabilities: \[gpu\]\r?\n'
    $updated = [regex]::Replace($content, $pattern, "`n")
    if ($updated -ne $content) {
        Set-Content -LiteralPath $ComposePath -Value $updated -Encoding UTF8
        Write-EveyLog -Message "Removed NVIDIA GPU reservation from docker-compose.yml." -LogFile $logFile
    }
}

function Install-PluginPreset {
    param([Parameter(Mandatory)][string]$Preset)

    if ($Preset -eq "skip") {
        Write-EveyLog -Message "Plugin install skipped." -LogFile $logFile
        return
    }

    $pluginDir = Join-Path $InstallDirectory "data/hermes/plugins"
    $cacheDir = Join-Path $InstallDirectory ".plugin-cache"
    New-EveyDirectory -Path $pluginDir

    if (Test-Path -LiteralPath (Join-Path $cacheDir ".git")) {
        $pull = Invoke-EveyNative -FilePath "git" -Arguments @("-C", $cacheDir, "pull", "--quiet") -LogFile $logFile
        if ($pull.ExitCode -ne 0) {
            throw "Could not update plugin repository. See $logFile"
        }
    } else {
        if (Test-Path -LiteralPath $cacheDir) {
            Remove-Item -LiteralPath $cacheDir -Recurse -Force
        }
        $clone = Invoke-EveyNative -FilePath "git" -Arguments @("clone", "--depth", "1", "https://github.com/42-evey/hermes-plugins.git", $cacheDir) -LogFile $logFile
        if ($clone.ExitCode -ne 0) {
            throw "Could not clone plugin repository. See $logFile"
        }
    }

    $core = @("evey-bridge", "evey-goals", "evey-delegate-model", "evey-status", "evey-cost-guard")
    $observability = @("evey-telemetry", "evey-watchdog", "evey-mqtt")
    $social = @("evey-moltbook", "evey-proactive", "evey-news")
    $memory = @("evey-memory-adaptive", "evey-memory-consolidate", "evey-learner", "evey-habits")
    $quality = @("evey-reflect", "evey-validate", "evey-council", "evey-email-guard")
    $extra = @("evey-autonomy", "evey-research", "evey-scheduler", "evey-digest", "evey-delegation-score", "evey-identity", "evey-session-guard", "evey-telegram-ux", "evey-sandbox", "evey-cache")

    $selected = if ($Preset -eq "all") {
        @($core + $observability + $social + $memory + $quality + $extra)
    } else {
        $core
    }

    $utils = Join-Path $cacheDir "evey_utils.py"
    if (Test-Path -LiteralPath $utils) {
        Copy-Item -LiteralPath $utils -Destination (Join-Path $pluginDir "evey_utils.py") -Force
    } else {
        throw "Plugin helper evey_utils.py was not found in plugin repository."
    }

    foreach ($name in $selected) {
        $src = Join-Path $cacheDir $name
        $dst = Join-Path $pluginDir $name
        if (Test-Path -LiteralPath $src) {
            if (Test-Path -LiteralPath $dst) {
                Remove-Item -LiteralPath $dst -Recurse -Force
            }
            Copy-Item -LiteralPath $src -Destination $dst -Recurse -Force
            Write-EveyLog -Message "Installed plugin $name." -LogFile $logFile
        } else {
            throw "Required plugin $name was not found in plugin repository."
        }
    }
}

Write-EveyLog -Message "Deploying Evey stack to $InstallDirectory with tier $Tier." -LogFile $logFile

New-EveyDirectory -Path $InstallDirectory
foreach ($dir in @(
    "config",
    "config/mosquitto",
    "config/searxng",
    "data/hermes/plugins",
    "data/hermes/skills",
    "data/hermes/cron",
    "data/hermes/memories",
    "data/hermes/workspace",
    "data/claude-bridge/inbox",
    "data/claude-bridge/outbox",
    "data/mqtt",
    "data/qdrant",
    "data/ntfy",
    "data/n8n",
    "data/uptimekuma",
    "dockerfiles",
    "scripts",
    "src"
)) {
    New-EveyDirectory -Path (Join-Path $InstallDirectory $dir)
}

$envPath = Join-Path $InstallDirectory ".env"
if (-not (Test-Path -LiteralPath $envPath)) {
    throw ".env is missing. Run the installer or Install-Evey.ps1 first; do not pass API keys on the command-line."
}

$envMap = Get-EnvMap -Path $envPath
foreach ($providerKey in Get-EveyModelProviderKeyNames) {
    if (-not $envMap.Contains($providerKey)) {
        $envMap[$providerKey] = ""
    }
}
if (-not (Test-EveyHasModelProviderKey -Map $envMap)) {
    throw "At least one AI provider API key is required. Add OPENAI_API_KEY, MOONSHOT_API_KEY, DASHSCOPE_API_KEY, ZAI_API_KEY, or OPENROUTER_API_KEY to .env."
}
Ensure-EnvValue -Map $envMap -Name "LITELLM_MASTER_KEY" -Value ("sk-litellm-" + (New-EveyToken -ByteCount 16))
Ensure-EnvValue -Map $envMap -Name "API_SERVER_KEY" -Value ("sk-api-" + (New-EveyToken -ByteCount 8))
Ensure-EnvValue -Map $envMap -Name "N8N_DB_PASSWORD" -Value (New-EveyToken -ByteCount 16)
Ensure-EnvValue -Map $envMap -Name "LANGFUSE_DB_PASSWORD" -Value (New-EveyToken -ByteCount 16)
Ensure-EnvValue -Map $envMap -Name "NEXTAUTH_SECRET" -Value (New-EveyToken -ByteCount 32)
Ensure-EnvValue -Map $envMap -Name "LANGFUSE_SALT" -Value (New-EveyToken -ByteCount 16)
Ensure-EnvValue -Map $envMap -Name "LANGFUSE_PUBLIC_KEY" -Value ("pk-lf-" + (New-EveyToken -ByteCount 12))
Ensure-EnvValue -Map $envMap -Name "LANGFUSE_SECRET_KEY" -Value ("sk-lf-" + (New-EveyToken -ByteCount 16))
Ensure-EnvValue -Map $envMap -Name "TZ" -Value ([System.TimeZoneInfo]::Local.Id)
Save-EnvMap -Map $envMap -Path $envPath

Copy-Template -RelativeSource "templates/litellm.yaml" -Destination (Join-Path $InstallDirectory "config/litellm.yaml")
Copy-Template -RelativeSource "templates/config.yaml" -Destination (Join-Path $InstallDirectory "data/hermes/config.yaml")

@"
listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest stdout
"@ | Set-Content -LiteralPath (Join-Path $InstallDirectory "config/mosquitto/mosquitto.conf") -Encoding UTF8

@"
use_default_settings: true
server:
  secret_key: "$(New-EveyToken -ByteCount 16)"
  limiter: false
search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
"@ | Set-Content -LiteralPath (Join-Path $InstallDirectory "config/searxng/settings.yml") -Encoding UTF8

$channel = Join-Path $InstallDirectory "data/claude-bridge/channel.jsonl"
if (-not (Test-Path -LiteralPath $channel)) { New-Item -ItemType File -Path $channel -Force | Out-Null }
$jobs = Join-Path $InstallDirectory "data/hermes/cron/jobs.json"
if (-not (Test-Path -LiteralPath $jobs)) { "[]" | Set-Content -LiteralPath $jobs -Encoding UTF8 }

$hermesSrc = Join-Path $InstallDirectory "src/hermes-agent"
if (-not (Test-Path -LiteralPath $hermesSrc)) {
    $clone = Invoke-EveyNative -FilePath "git" -Arguments @("clone", "--depth", "1", "https://github.com/NousResearch/hermes-agent.git", $hermesSrc) -LogFile $logFile
    if ($clone.ExitCode -ne 0) {
        throw "Could not clone NousResearch/hermes-agent. See $logFile"
    }
} else {
    Write-EveyLog -Message "hermes-agent source already exists." -LogFile $logFile
}

$composeName = "templates/docker-compose.$Tier.yml"
# Supported templates: templates/docker-compose.base.yml, templates/docker-compose.services.yml,
# templates/docker-compose.full.yml.
$composePath = Join-Path $InstallDirectory "docker-compose.yml"
Copy-Template -RelativeSource $composeName -Destination $composePath
Remove-GpuBlockIfNeeded -ComposePath $composePath

Install-PluginPreset -Preset $PluginPreset

if (-not $SkipDockerUp) {
    $up = Invoke-EveyNative -FilePath "docker" -Arguments @("compose", "up", "-d", "--build") -WorkingDirectory $InstallDirectory -LogFile $logFile
    if ($up.ExitCode -ne 0) {
        throw "docker compose up -d --build failed. See $logFile"
    }
} else {
    Write-EveyLog -Message "Skipping docker compose up -d --build because -SkipDockerUp was set." -LogFile $logFile
}

$state = Read-EveyState
$state.installDirectory = $InstallDirectory
$state.selectedTier = $Tier
$state.selectedPluginPreset = $PluginPreset
$state.lastLogDirectory = $logDir
$state.completedStages = @("deploy")
Save-EveyState -State $state | Out-Null

[ordered]@{
    installDirectory = $InstallDirectory
    tier = $Tier
    pluginPreset = $PluginPreset
    logDirectory = $logDir
    skippedDockerUp = [bool]$SkipDockerUp
}
