param(
    [string]$InstallDirectory = (Join-Path $HOME "evey-stack"),
    [ValidateSet("base", "services", "full")]
    [string]$Tier = "base",
    [ValidateSet("core", "all", "skip")]
    [string]$PluginPreset = "core",
    [switch]$AcceptDockerNotice,
    [switch]$RunPrerequisiteActions,
    [switch]$SkipDeploy,
    [switch]$SkipDockerUp
)

. "$PSScriptRoot/EveyCommon.ps1"

function ConvertFrom-SecureInput {
    param([Parameter(Mandatory)]$SecureString)

    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

function Ensure-InstallerEnv {
    param([Parameter(Mandatory)][string]$Path)

    $envPath = Join-Path $Path ".env"
    if (Test-Path -LiteralPath $envPath) {
        Protect-EveyFile -Path $envPath
        return $envPath
    }

    $providerDefaults = Get-EveyModelProviderDefaults
    Write-Host "Model provider setup is optional. You can deploy Hermes now and configure models or account login later."
    $openAiSecure = Read-Host "OpenAI API key (optional, press Enter to skip)" -AsSecureString
    $moonshotSecure = Read-Host "Kimi / Moonshot API key (optional, press Enter to skip)" -AsSecureString
    $dashscopeSecure = Read-Host "Qwen / DashScope API key (optional, press Enter to skip)" -AsSecureString
    $zaiSecure = Read-Host "GLM / Z.AI API key (optional, press Enter to skip)" -AsSecureString
    $openRouterSecure = Read-Host "OpenRouter API key (optional, press Enter to skip)" -AsSecureString

    Write-Host "Provider URLs are optional. Press Enter to use the default URL shown in brackets."
    $openAiBase = Read-Host "OpenAI API URL [$($providerDefaults['OPENAI_API_BASE'])]"
    if (-not $openAiBase) { $openAiBase = $providerDefaults['OPENAI_API_BASE'] }
    $moonshotBase = Read-Host "Kimi / Moonshot API URL [$($providerDefaults['MOONSHOT_API_BASE'])]"
    if (-not $moonshotBase) { $moonshotBase = $providerDefaults['MOONSHOT_API_BASE'] }
    $dashscopeBase = Read-Host "Qwen / DashScope API URL [$($providerDefaults['DASHSCOPE_API_BASE'])]"
    if (-not $dashscopeBase) { $dashscopeBase = $providerDefaults['DASHSCOPE_API_BASE'] }
    $zaiBase = Read-Host "GLM / Z.AI API URL [$($providerDefaults['ZAI_API_BASE'])]"
    if (-not $zaiBase) { $zaiBase = $providerDefaults['ZAI_API_BASE'] }
    $openRouterBase = Read-Host "OpenRouter API URL [$($providerDefaults['OPENROUTER_API_BASE'])]"
    if (-not $openRouterBase) { $openRouterBase = $providerDefaults['OPENROUTER_API_BASE'] }

    $telegramSecure = Read-Host "Telegram bot token (optional, press Enter to skip)" -AsSecureString
    $discordSecure = Read-Host "Discord bot token (optional, press Enter to skip)" -AsSecureString

    $openAi = ConvertFrom-SecureInput -SecureString $openAiSecure
    $moonshot = ConvertFrom-SecureInput -SecureString $moonshotSecure
    $dashscope = ConvertFrom-SecureInput -SecureString $dashscopeSecure
    $zai = ConvertFrom-SecureInput -SecureString $zaiSecure
    $openRouter = ConvertFrom-SecureInput -SecureString $openRouterSecure
    $telegram = ConvertFrom-SecureInput -SecureString $telegramSecure
    $discord = ConvertFrom-SecureInput -SecureString $discordSecure

    @(
        "# Evey Stack - generated by Windows installer",
        "OPENAI_API_KEY=$openAi",
        "OPENAI_API_BASE=$openAiBase",
        "MOONSHOT_API_KEY=$moonshot",
        "MOONSHOT_API_BASE=$moonshotBase",
        "DASHSCOPE_API_KEY=$dashscope",
        "DASHSCOPE_API_BASE=$dashscopeBase",
        "ZAI_API_KEY=$zai",
        "ZAI_API_BASE=$zaiBase",
        "OPENROUTER_API_KEY=$openRouter",
        "OPENROUTER_API_BASE=$openRouterBase",
        "TELEGRAM_BOT_TOKEN=$telegram",
        "DISCORD_BOT_TOKEN=$discord"
    ) | Set-Content -LiteralPath $envPath -Encoding UTF8

    Protect-EveyFile -Path $envPath
    return $envPath
}

function Invoke-EveyPrerequisiteAction {
    param(
        [Parameter(Mandatory)]$Action,
        [Parameter(Mandatory)][System.Collections.IDictionary]$State,
        [Parameter(Mandatory)][string]$LogFile
    )

    if (-not $RunPrerequisiteActions) {
        return $false
    }

    Write-EveyLog -Message "Running prerequisite action: $($Action.name)" -LogFile $LogFile
    if ($Action.name -like "*WSL*") {
        $State.pendingRestartReason = "WSL setup may require a Windows restart."
        Save-EveyState -State $State | Out-Null
        $result = Invoke-EveyNative -FilePath "wsl.exe" -Arguments @("--install") -LogFile $LogFile
        if ($result.ExitCode -ne 0) {
            throw "WSL setup failed or was cancelled. See $LogFile"
        }
        return $true
    }

    if ($Action.name -like "*Git*") {
        if (-not (Test-EveyCommand "winget.exe")) {
            Write-EveyLog -Level "WARN" -Message "winget.exe was not found; Git must be installed manually." -LogFile $LogFile
            return $false
        }
        $result = Invoke-EveyNative -FilePath "winget.exe" -Arguments @("install", "--id", "Git.Git", "-e") -LogFile $LogFile
        if ($result.ExitCode -ne 0) {
            throw "Git installation through winget failed or was cancelled. See $LogFile"
        }
        return $true
    }

    if ($Action.name -like "*Docker Desktop*") {
        if (-not $AcceptDockerNotice) {
            throw "Docker Desktop notice must be acknowledged before opening Docker installation."
        }
        Start-Process "https://docs.docker.com/desktop/setup/install/windows-install/"
        Write-EveyLog -Message "Opened Docker Desktop install page. User must install Docker Desktop and accept Docker terms directly." -LogFile $LogFile
        return $true
    }

    if ($Action.name -eq "Start-EveyDockerDesktop") {
        Start-EveyDockerDesktop -LogFile $LogFile
        return $true
    }

    return $false
}

function Start-EveyDockerDesktop {
    param([Parameter(Mandatory)][string]$LogFile)

    $paths = @(
        "$env:ProgramFiles\Docker\Docker\Docker Desktop.exe",
        "$env:LocalAppData\Docker\Docker Desktop.exe"
    )
    $dockerDesktop = $paths | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
    if (-not $dockerDesktop) {
        throw "Docker Desktop is not installed."
    }
    Start-Process -FilePath $dockerDesktop
    Write-EveyLog -Message "Started Docker Desktop; waiting for Docker daemon." -LogFile $LogFile
    for ($i = 0; $i -lt 60; $i++) {
        Start-Sleep -Seconds 5
        $info = Invoke-EveyNative -FilePath "docker.exe" -Arguments @("info") -LogFile $LogFile
        if ($info.ExitCode -eq 0) {
            return
        }
    }
    throw "Docker Desktop did not become ready within 5 minutes."
}

$runId = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
$logDir = Get-EveyLogDirectory -RunId $runId
$logFile = Join-Path $logDir "install.log"
$statePath = Get-EveyStatePath # %ProgramData%\EveySetup\install-state.json

Write-EveyLog -Message "Starting Evey Windows install." -LogFile $logFile
Write-EveyLog -Message "Resume state file: $statePath" -LogFile $logFile
New-EveyDirectory -Path $InstallDirectory

$state = Read-EveyState
$state.installerVersion = "0.1.0-internal-test"
$state.installDirectory = $InstallDirectory
$state.selectedTier = $Tier
$state.selectedPluginPreset = $PluginPreset
$state.lastLogDirectory = $logDir
$state.installStatus = "running"
$state.completedStages = @()
Assert-EveyStateHasNoSecrets -State $state
Save-EveyState -State $state | Out-Null

$prereqJson = Join-Path $logDir "prereq-report.json"
$prereqArgs = @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $PSScriptRoot "Test-EveyPrereqs.ps1"),
    "-InstallDirectory", $InstallDirectory,
    "-JsonPath", $prereqJson
)
if ($AcceptDockerNotice) {
    $prereqArgs += "-AcceptDockerNotice"
}

$prereq = Invoke-EveyNative -FilePath "powershell.exe" -Arguments $prereqArgs -LogFile $logFile
if ($prereq.ExitCode -ne 0) {
    Write-EveyLog -Level "WARN" -Message "Prerequisite checker exited with code $($prereq.ExitCode)." -LogFile $logFile
}

$report = Get-Content -LiteralPath $prereqJson -Raw | ConvertFrom-Json
$state.lastPrerequisiteReportPath = $prereqJson
if ($report.pendingRestartReason) {
    $state.pendingRestartReason = $report.pendingRestartReason
}
Save-EveyState -State $state | Out-Null

if (-not $report.passed) {
    $ranAction = $false
    foreach ($action in @($report.actions)) {
        if (Invoke-EveyPrerequisiteAction -Action $action -State $state -LogFile $logFile) {
            $ranAction = $true
        }
    }
    if ($ranAction) {
        $state.installStatus = "blocked-prerequisites"
        Save-EveyState -State $state | Out-Null
        Write-EveyLog -Level "WARN" -Message "Prerequisite action completed. Re-run the installer after installing/restarting as needed." -LogFile $logFile
        exit 21
    }
    Write-EveyLog -Level "WARN" -Message "Prerequisites are not ready. See $prereqJson." -LogFile $logFile
    $state.installStatus = "blocked-prerequisites"
    Save-EveyState -State $state | Out-Null
    Write-Host ""
    Write-Host "This PC is not ready yet. Open the report below for the exact next steps:"
    Write-Host $prereqJson
    exit 20
}

Ensure-InstallerEnv -Path $InstallDirectory | Out-Null
$state.completedStages = @("prerequisites", "env")
Save-EveyState -State $state | Out-Null

if ($SkipDeploy) {
    $state.installStatus = "skipped-deploy"
    Save-EveyState -State $state | Out-Null
    throw "Deployment was skipped, so the installer cannot report success."
}

$deployArgs = @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $PSScriptRoot "Deploy-EveyStack.ps1"),
    "-InstallDirectory", $InstallDirectory,
    "-Tier", $Tier,
    "-PluginPreset", $PluginPreset,
    "-SourceRoot", (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
)
if ($SkipDockerUp) {
    $deployArgs += "-SkipDockerUp"
}
$deploy = Invoke-EveyNative -FilePath "powershell.exe" -Arguments $deployArgs -WorkingDirectory $InstallDirectory -LogFile $logFile
if ($deploy.ExitCode -ne 0) {
    $state.installStatus = "failed"
    Save-EveyState -State $state | Out-Null
    throw "Deployment failed. See $logFile"
}

$verifyArgs = @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $PSScriptRoot "Test-EveyInstall.ps1"),
    "-InstallDirectory", $InstallDirectory,
    "-Tier", $Tier,
    "-FailOnError"
)
$verify = Invoke-EveyNative -FilePath "powershell.exe" -Arguments $verifyArgs -WorkingDirectory $InstallDirectory -LogFile $logFile
if ($verify.ExitCode -ne 0) {
    $state.installStatus = "failed"
    Save-EveyState -State $state | Out-Null
    throw "Post-install verification failed. See $logFile"
}

$state.completedStages = @("prerequisites", "env", "deploy", "verify")
$state.installStatus = "success"
Save-EveyState -State $state | Out-Null

Write-EveyLog -Message "Evey Windows install flow finished. Logs: $logDir" -LogFile $logFile
Write-Host ""
Write-Host "Evey setup completed successfully. Logs are saved here:"
Write-Host $logDir
